name: Main

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  instaplanner-build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'ci skip') == false

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: redis, mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug
        tools: composer, php-cs-fixer

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: Build
      run: |
        composer install
        npm install
        npm run build

    - name: 'Create artifact archive'
      run: zip instaplanner-build.zip ./* -r

    - name: 'Archive results'
      uses: actions/upload-artifact@v2
      with:
        name: instaplanner-build
        path: instaplanner-build.zip